#!/bin/bash
docker run --rm -it \
  -v `pwd`:/opt/git-repo \
  -v $HOME/.gitconfig:/root/.gitconfig \
  -v $HOME/.ssh/id_rsa:/root/.ssh/id_rsa \
  -v $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub \
  -v $HOME/.ssh/known_hosts:/root/.ssh/known_hosts \
  gafonso21/git "$@"
